---
- name: Fail if required variables are not defined
  assert:
    that: ("{{ item }} is defined") and ("{{ item }} | length > 0")
  loop:
    - nginx_controller_fqdn
    - nginx_controller_auth_token
    - nginx_controller_environment
    - nginx_controller_application
    - nginx_controller_publish_api.metadata.name
    - nginx_controller_publish_api.desiredState.apiDefinitionVersionRef.ref
    - nginx_controller_publish_api.desiredState.gatewayRefs[0]

- name: Form the publish_api API url
  set_fact:
    publish_api_url: "https://{{ nginx_controller_fqdn }}/{{ nginx_controller_api_version }}/services/environments/{{ nginx_controller_environment }}/apps/{{ nginx_controller_application }}/published-apis/{{ nginx_controller_publish_api.metadata.name }}"

- name: Upsert publish_api (create if absent, change if present)
  uri:
    url: "{{ publish_api_url }}"
    method: "PUT"
    body: "{{ nginx_controller_publish_api }}"
    body_format: json
    status_code:
      - 200
      - 201
      - 202
    return_content: yes
    validate_certs: "{{ nginx_controller_validate_certs | default(false) }}"
    headers:
      Cookie: "{{ nginx_controller_auth_token }}"
  register: nginx_controller_publish_api_status

- name: Show publish_api status
  debug:
    msg: "{{ nginx_controller_publish_api_status }}"

# - name: Capture publish_api reference
#   set_fact:
#     nginx_controller_publish_api_reference: "{{ nginx_controller_publish_api_status.json.metadata.links.rel }}"

# - name: Show publish_api reference
#   debug:
#     msg: "{{ nginx_controller_publish_api_reference }}"
